services:
  omg-shopify:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./product_mappings.json:/project/product_mappings.json
      - ./static:/project/static
      - ./data:/project/data
    restart: unless-stopped
