"""Retro-fit Mango's gpt-image-2 proportional-print model scenes onto an
already-approved tee.

Use this when:
- You want to upgrade a tee that was approved before 2026-05-06 (when the
  proportional pipeline was wired into Mango's approval flow).
- A fresh approval ran but the proportional scenes failed and you want to
  re-run just that step.
- You want to regenerate scenes for any reason (tee color change, design
  edit, etc.).

For each handle: generates the 8 model scenes (man+woman × close+full ×
front+back) using the design PNG + the existing 04_hanger_back.png as
the size anchor. Then uploads to the live OMG Shopify product with
gender × placement variant linking, appended to the end of the gallery.

Usage:
  # Single tee:
  .venv/Scripts/python -m scripts.regenerate_proportional_scenes \\
      certified-couch-potato-brutalist-typography-tee

  # Several:
  .venv/Scripts/python -m scripts.regenerate_proportional_scenes \\
      sexi-madafaka-greek-slogan-tee chaos-coordinator-professional-multitasker-tee

  # ALL active text+image tees (excludes 5 astous tees that use real
  # photos — see project_live_marketing_scope memory):
  .venv/Scripts/python -m scripts.regenerate_proportional_scenes --all

  # Dry-run — see what it would do without API calls or uploads:
  .venv/Scripts/python -m scripts.regenerate_proportional_scenes --all --dry-run

Cost: ~$1.50/tee (8 × gpt-image-2 high-quality image-edit calls).
Time: ~10 min/tee at concurrency=2.
"""
from __future__ import annotations

import argparse
import asyncio
import logging
import os
import sys
from pathlib import Path

import httpx

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.stdout.reconfigure(encoding="utf-8")

from dotenv import load_dotenv  # noqa: E402
load_dotenv(ROOT / ".env")

from app.agents.eurovision_scenes import generate_proportional_scenes  # noqa: E402
from app.shopify_product_creator import upload_product_image  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

DOMAIN = "52922c-2.myshopify.com"
TOKEN = os.environ.get("OMG_SHOPIFY_ADMIN_TOKEN", "")
H = {"X-Shopify-Access-Token": TOKEN}

# Astous tees use real product photography — see CLAUDE.md / memory
# project_live_marketing_scope. Don't generate AI scenes for these.
ASTOUS_EXCLUDE = {
    "astous-na-laloun-cyprus-female-tee",
    "astous-na-laloun-cyprus-male-tee",
    "astous-na-laloun-cyprus-female-limited-tee",
    "astous-na-laloun-cyprus-male-limited-tee",
    # Note: astous-na-laloun-cyprus-unisex-tee is intentionally NOT excluded
    # — it has Eurovision-style scenes from the original Astous launch.
}

# Variant-link mapping: scene label → (gender_variant, placement_variant)
SCENE_VARIANT_MAP = {
    "01_female_front_close": ("female", "front"),
    "02_female_front_full":  ("female", "front"),
    "03_male_front_close":   ("male",   "front"),
    "04_male_front_full":    ("male",   "front"),
    "01_female_back_close":  ("female", "back"),
    "02_female_back_full":   ("female", "back"),
    "03_male_back_close":    ("male",   "back"),
    "04_male_back_full":     ("male",   "back"),
}


def _resolve_design_path(handle: str) -> Path | None:
    """Find the design PNG for this handle. Tries the standard slot
    first; some products have variants like .original.png."""
    candidates = [
        ROOT / "static" / f"design_{handle}.png",
    ]
    for c in candidates:
        if c.exists():
            return c
    return None


def _resolve_anchor_path(handle: str) -> Path | None:
    """Find this design's hanger photo. Generated by Mango's
    compose_marketing_scenes — lives at proposals/<slug>/04_hanger_back.png
    where slug = handle with hyphens replaced by underscores."""
    slug = handle.replace("-", "_")
    candidates = [
        ROOT / "static" / "proposals" / handle / "04_hanger_back.png",
        ROOT / "static" / "proposals" / slug / "04_hanger_back.png",
    ]
    for c in candidates:
        if c.exists():
            return c
    return None


def _fetch_product(handle: str) -> dict | None:
    with httpx.Client(timeout=30) as c:
        r = c.get(
            f"https://{DOMAIN}/admin/api/2024-01/products.json",
            headers=H, params={"handle": handle},
        )
        r.raise_for_status()
        prods = r.json().get("products", [])
        return prods[0] if prods else None


def _variant_groups(product: dict) -> dict[tuple[str, str], list[int]]:
    """Map (gender, placement) -> list of variant_ids."""
    out: dict[tuple[str, str], list[int]] = {
        ("male", "front"): [], ("male", "back"): [],
        ("female", "front"): [], ("female", "back"): [],
    }
    for v in product.get("variants", []):
        gender = (v.get("option1") or "").lower()
        placement = (v.get("option2") or "").lower()
        gkey = "female" if "female" in gender else ("male" if "male" in gender else None)
        pkey = "back" if placement == "back" else ("front" if placement == "front" else None)
        if gkey and pkey:
            out[(gkey, pkey)].append(v["id"])
    return out


def _list_active_handles() -> list[str]:
    handles = []
    with httpx.Client(timeout=30) as c:
        r = c.get(
            f"https://{DOMAIN}/admin/api/2024-01/products.json",
            headers=H, params={"status": "active", "limit": 250},
        )
        r.raise_for_status()
        for p in r.json().get("products", []):
            h = p["handle"]
            if h in ASTOUS_EXCLUDE:
                continue
            # Active OMG product must have Male+Female variants to qualify
            titles = " ".join(v.get("title", "") for v in p.get("variants", []))
            if "Male" not in titles or "Female" not in titles:
                continue
            handles.append(h)
    return sorted(handles)


async def process_handle(handle: str, dry_run: bool = False) -> None:
    print(f"\n=== {handle} ===")
    design_path = _resolve_design_path(handle)
    if not design_path:
        print(f"  SKIP — no design PNG at static/design_{handle}.png")
        return
    anchor_path = _resolve_anchor_path(handle)
    if not anchor_path:
        print(
            f"  WARNING — no 04_hanger_back.png anchor found in "
            f"static/proposals/{handle}/ (or slug variant). Print may render "
            f"oversized."
        )
    product = _fetch_product(handle)
    if not product:
        print(f"  SKIP — product not found on Shopify")
        return

    out_dir = ROOT / "static" / "proposals" / handle.replace("-", "_") / "_proportional"
    print(f"  design: {design_path.name}")
    print(f"  anchor: {anchor_path.name if anchor_path else 'none'}")
    print(f"  out_dir: {out_dir}")

    if dry_run:
        print("  (dry-run — no API calls)")
        return

    scenes = await generate_proportional_scenes(
        design_path=design_path, anchor_path=anchor_path, out_dir=out_dir, slug=handle,
    )
    print(f"  generated {len(scenes)}/8 scenes")

    groups = _variant_groups(product)
    pid = product["id"]
    for label, path in scenes.items():
        gender, placement = SCENE_VARIANT_MAP[label]
        vids = groups[(gender, placement)] or None
        try:
            img = await upload_product_image(
                pid, path, alt=f"{product['title']} — {label.replace('_',' ')}",
                variant_ids=vids,
            )
            print(f"  uploaded {label}: pos={img.get('position')} vars={len(img.get('variant_ids') or [])}")
        except Exception as e:
            print(f"  FAILED {label}: {e}")


async def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("handles", nargs="*", help="Product handles to retro-fit")
    parser.add_argument("--all", action="store_true", help="Process every active tee (excl. astous)")
    parser.add_argument("--dry-run", action="store_true", help="Print plan without API calls")
    args = parser.parse_args()

    if args.all:
        handles = _list_active_handles()
        print(f"--all → {len(handles)} active tees")
    else:
        handles = args.handles
        if not handles:
            sys.exit("No handles given. Pass one or more, or --all.")

    for h in handles:
        await process_handle(h, dry_run=args.dry_run)


if __name__ == "__main__":
    asyncio.run(main())
